package main

var implTpl = `
// Code generated by thrift-gen-kitex-reflect. DO NOT EDIT.
package {{ .PkgName }}

import (
	idl "github.com/jxskiss/kitex-reflect/kitex_gen/kitexreflectidl"
)

func init() {
	serviceInfo().Methods["ReflectService"] = PluginReflect.NewMethodInfo()
}

func GetReflectServiceRespPayload() *idl.ReflectServiceRespPayload {
	return PluginReflect.NewRespPayload()
}

func GetIDLRawBytes() []byte {
	return idlRawBytes
}

var PluginReflect = &idl.PluginImpl{
	Version: "{{ .GenTime }}",

	GetIDLBytes: func() []byte { return idlRawBytes },
}

var idlRawBytes = []byte{
{{ .IDLBytes }}
}
`
