package main

var implTpl = `
// Code generated by thrift-gen-kitex-reflect. DO NOT EDIT.
package {{ .PkgName }}

import (
	idl "github.com/jxskiss/kitex-reflect/kitex_gen/kitexreflectidl"
)

{{- if .Args.AutoSetup }}
func init() {
	SetupReflectPluginMethods()
}
{{- end }}

func SetupReflectPluginMethods() {
	serviceInfo().Methods["ReflectService"] = PluginReflect.NewMethodInfo()
}

func GetReflectServiceRespPayload() *idl.ReflectServiceRespPayload {
	return PluginReflect.NewRespPayload()
}

func GetIDLRawBytes() []byte {
	return idlRawBytes
}

var PluginReflect = &idl.PluginImpl{
	Version: "{{ .GenTime }}",
	IsCombineService: {{ .Args.IsCombineService }},

	GetIDLBytes: func() []byte { return idlRawBytes },
}

var idlRawBytes = []byte{
{{ .IDLBytes }}
}
`
